spring :
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none